from typing import Any, List, NotRequired, TypedDict
from langchain_core.documents import Document

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    
    Attributes:
        question: The user's original or rewritten question
        generation: The final answer generated by the LLM
        documents: A list of retrieved documents
        retry_count: How many times we've tried to fix the search
    """
    question: str
    generation: str
    documents: List[Document]
    retry_count: int

    # --- Debug fields for tracing (LangSmith) ---
    # Metadata-only (no document text) so it’s safe to log.
    retrieved_docs_meta: NotRequired[List[dict[str, Any]]]
    doc_grades: NotRequired[List[dict[str, Any]]]
    used_docs_meta: NotRequired[List[dict[str, Any]]]