from typing import List, TypedDict
from langchain_core.documents import Document

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    
    Attributes:
        question: The user's original or rewritten question
        generation: The final answer generated by the LLM
        documents: A list of retrieved documents
        retry_count: How many times we've tried to fix the search
    """
    question: str
    generation: str
    documents: List[Document]
    retry_count: int